# Generated by Django 4.2.7 on 2023-11-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_brand_listing_color_listing_descripton_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='transmission',
            new_name='transmisson',
        ),
    ]
